const { sequelize, Produto, InformacoesLogin, Venda, Compra } = require('./models');

(async () => {
  try {
    // Sincroniza o banco de dados
    await sequelize.sync({ force: true }); // Use `force: true` para recriar o banco a cada execução
    console.log('Banco sincronizado com sucesso!');

    // Insere dados iniciais em `informacoeslogin`
    const usuarios = [
      { login: 'LChaveszzz', senha: 'Lc+lf@123', nome: 'Liandro Chaves', empresa: ' L&FTecnologies' },
    ];
    await InformacoesLogin.bulkCreate(usuarios);
    console.log('Dados de login inseridos com sucesso!');

    // Insere dados iniciais em `produtos`
    const produtos = [
        { nome: 'Notebook Dell Inspiron', categoria: 'Informática', subcategoria: 'Notebooks', estoque: 25, preco: 4999.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "O Notebook Dell Inspiron é uma linha de computadores portáteis que combina desempenho, design e praticidade, ideal tanto para uso pessoal quanto profissional. Equipado com processadores poderosos, como os da linha Intel Core ou AMD Ryzen, oferece uma experiência de uso fluida para tarefas cotidianas, como navegação na web, edição de documentos e consumo de conteúdo multimídia. Seu display de alta definição proporciona imagens nítidas e claras, enquanto a construção robusta garante durabilidade. Com uma variedade de opções de armazenamento, como SSDs e HDDs, e conectividade Wi-Fi 6, o Dell Inspiron se adapta bem às necessidades de quem busca um notebook confiável e eficiente para o dia a dia.", imagem: "/uploads/image-1738025760373-988225569.webp"},
        { nome: 'Monitor LG 24" Full HD', categoria: 'Informática', subcategoria: 'Monitores', estoque: 30, preco: 1199.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "O Monitor LG 24 Full HD oferece uma excelente experiência visual com sua resolução de 1920x1080 pixels, proporcionando imagens nítidas e vibrantes para diversas atividades, como trabalho, entretenimento e jogos. Com a tecnologia IPS, garante cores precisas e consistentes de qualquer ângulo, enquanto seu design moderno e elegante se adapta perfeitamente a qualquer ambiente. O tamanho de 24 polegadas é ideal para quem busca produtividade e conforto, e suas entradas HDMI e VGA proporcionam flexibilidade de conexão. Além disso, o monitor conta com recursos que reduzem a fadiga ocular, oferecendo mais conforto durante o uso prolongado.", imagem: "/uploads/image-1738018965752-578259551.webp"},
        { nome: 'Teclado Mecânico Redragon', categoria: 'Periféricos', subcategoria: 'Teclados', estoque: 40, preco: 299.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao:"O Teclado Mecânico Redragon é uma excelente escolha para quem busca desempenho e conforto em jogos ou produtividade. Com switches mecânicos de alta qualidade, ele proporciona uma resposta tátil e precisa, ideal para longas sessões de digitação ou jogos intensos. O design robusto e moderno conta com retroiluminação RGB personalizável, permitindo criar ambientes únicos. Além disso, o teclado é equipado com teclas anti-ghosting e N-key rollover, garantindo que todas as teclas pressionadas sejam registradas simultaneamente. Sua construção durável e resistente é projetada para suportar o uso intenso, oferecendo uma experiência superior a qualquer usuário." , imagem: "/uploads/image-1738019060757-999907621.webp"},
        { nome: 'Mouse Gamer Logitech G502', categoria: 'Periféricos', subcategoria: 'Mouses', estoque: 50, preco: 349.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao:"O Mouse Gamer Logitech G502 é sinônimo de precisão e desempenho, perfeito para jogadores exigentes. Com sensor HERO 25K, oferece resolução ajustável de até 25.600 DPI, garantindo extrema precisão em movimentos rápidos. Possui 11 botões programáveis, sistema de pesos ajustáveis e iluminação RGB personalizável através do software Logitech G HUB. Seu design ergonômico e materiais de alta qualidade proporcionam conforto durante longas sessões de jogo. Ideal para quem busca controle absoluto e desempenho superior em todos os tipos de games." , imagem:"/uploads/image-1738025020443-747345069.jpg" },
        { nome: 'Câmera Logitech C920 HD', categoria: 'Periféricos', subcategoria: 'Webcams', estoque: 20, preco: 499.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "A Câmera Logitech C920 HD é ideal para quem busca qualidade superior em chamadas de vídeo, gravações ou transmissões ao vivo. Com resolução Full HD 1080p, ela captura imagens nítidas e vibrantes, proporcionando uma experiência profissional. Seu foco automático e as lentes de vidro garantem detalhes precisos, enquanto os microfones duplos embutidos captam o som de forma clara e natural. Compacta e fácil de instalar, a C920 é compatível com diversas plataformas e oferece desempenho confiável tanto para trabalho quanto para lazer.", imagem: "/uploads/image-1738019329559-87713181.webp"},
        { nome: 'SSD Kingston 1TB', categoria: 'Armazenamento', subcategoria: 'SSDs', estoque: 35, preco: 649.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "O SSD Kingston 1TB combina desempenho excepcional e alta capacidade de armazenamento para turbinar seu sistema. Com tecnologia NVMe ou SATA (dependendo do modelo), oferece velocidades de leitura e gravação impressionantes, proporcionando inicialização rápida, carregamento ágil de aplicativos e transferência de dados eficiente. Sua capacidade de 1TB garante amplo espaço para armazenar arquivos, jogos e projetos com segurança. Compacto, resistente a choques e silencioso, é a escolha ideal para quem busca modernizar seu computador ou notebook com confiabilidade e velocidade.", imagem: "/uploads/image-1738025091551-947845080.webp"},
        { nome: 'HD Externo Seagate 2TB', categoria: 'Armazenamento', subcategoria: 'HDs Externos', estoque: 25, preco: 599.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao:"O HD Externo Seagate 2TB oferece uma solução prática e eficiente para armazenar todos os seus arquivos importantes. Com 2TB de capacidade, você terá espaço suficiente para guardar fotos, vídeos, documentos e muito mais. Sua conexão USB 3.0 garante uma transferência de dados rápida, enquanto o design compacto e portátil facilita o transporte. Ideal para quem busca segurança e praticidade no armazenamento de grandes volumes de dados. Perfeito para uso pessoal ou profissional, garantindo alto desempenho e confiabilidade." , imagem:"/uploads/image-1738021440367-854306499.png" },
        { nome: 'iPhone 14', categoria: 'Smartphones', subcategoria: 'Apple', estoque: 10, preco: 7999.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "O iPhone 14 eleva a experiência mobile com um design sofisticado e um desempenho incrível. Equipado com o poderoso chip A15 Bionic, oferece velocidade e eficiência energética superiores, além de uma câmera de última geração que captura fotos e vídeos impressionantes, mesmo em baixa luz. Sua tela Super Retina XDR proporciona cores vibrantes e nitidez excepcional, ideal para entretenimento e produtividade. Com recursos avançados como detecção de acidente, conectividade 5G e maior duração de bateria, o iPhone 14 é perfeito para quem busca inovação, estilo e desempenho em um único dispositivo.", imagem: "/uploads/image-1738025125032-348670373.jpg"},
        { nome: 'Samsung Galaxy S22', categoria: 'Smartphones', subcategoria: 'Android', estoque: 15, preco: 5999.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "O Samsung Galaxy S22 combina design elegante e desempenho de ponta para entregar uma experiência premium. Equipado com o processador Exynos 2200 ou Snapdragon 8 Gen 1 (dependendo da região), oferece velocidade incrível e eficiência energética. Sua tela Dynamic AMOLED 2X de 6,1 exibe cores vibrantes e fluidez impressionante, ideal para jogos e streaming. A câmera tripla captura fotos e vídeos com qualidade profissional, mesmo em ambientes de pouca luz, graças à tecnologia Nightography. Com bateria duradoura, conectividade 5G e recursos avançados como resistência à água (IP68) e carregamento rápido, o Galaxy S22 é perfeito para quem busca estilo e desempenho em um só aparelho.", imagem:"/uploads/image-1738025214911-504528900.jpg"  },
        { nome: 'Fone de Ouvido JBL Tune', categoria: 'Áudio', subcategoria: 'Fones Bluetooth', estoque: 60, preco: 299.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "Os Fones de Ouvido JBL Tune oferecem uma experiência de áudio envolvente com a assinatura sonora JBL Pure Bass, garantindo graves potentes e som de alta qualidade. Com design leve e confortável, são perfeitos para uso prolongado, seja no trabalho, durante exercícios ou no lazer. Disponíveis em versões com e sem fio, contam com bateria de longa duração e recursos modernos, como conexão Bluetooth estável e integração com assistentes de voz. Além disso, possuem controles intuitivos e microfone embutido, facilitando chamadas e ajustes rápidos. Uma opção versátil e estilosa para quem busca qualidade sonora em qualquer momento do dia.", imagem: "/uploads/image-1738025294266-353354157.webp"},
        { nome: 'Caixa de Som Alexa Echo', categoria: 'Áudio', subcategoria: 'Assistentes Virtuais', estoque: 40, preco: 399.0, catalogo: 'Não', favorito: false, usuario_id: 1,descricao: 'A Caixa de Som Alexa Echo é a combinação perfeita de tecnologia, elegância e praticidade. Com um design moderno que se adapta a qualquer ambiente, ela oferece um som poderoso e claro, ideal para transformar sua experiência de áudio em casa. Além de ser uma caixa de som de alta qualidade, a Alexa Echo é sua assistente pessoal, permitindo que você controle músicas, obtenha informações em tempo real, automatize dispositivos inteligentes e mantenha sua rotina organizada apenas com a sua voz. É mais do que um dispositivo; é a conexão perfeita entre inovação e comodidade no seu dia a dia.', imagem: "/uploads/alexa.jpg" },
        { nome: 'Placa de Vídeo RTX 3060', categoria: 'Hardware', subcategoria: 'Placas de Vídeo', estoque: 12, preco: 2499.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao:"A Placa de Vídeo NVIDIA GeForce RTX 3060 é a escolha ideal para gamers e criadores que buscam desempenho avançado. Equipada com 12GB de memória GDDR6 e arquitetura NVIDIA Ampere, oferece suporte a tecnologias como Ray Tracing e DLSS, garantindo gráficos realistas e alta taxa de quadros nos jogos mais exigentes. Projetada para entregar eficiência e potência, é compatível com resoluções até 4K e perfeita para tarefas como edição de vídeo, renderização e modelagem 3D. Com resfriamento otimizado e desempenho consistente, a RTX 3060 eleva a experiência visual a um novo nível." , imagem: "/uploads/image-1738025340740-548560422.jpg"},
        { nome: 'Processador Ryzen 5 5600X', categoria: 'Hardware', subcategoria: 'Processadores', estoque: 18, preco: 1099.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "O Processador Ryzen 5 5600X combina desempenho e eficiência, sendo ideal para gamers e criadores de conteúdo. Com 6 núcleos, 12 threads e uma velocidade de clock de até 4,6 GHz em modo turbo, oferece alta performance em multitarefas e jogos exigentes. Compatível com o soquete AM4, ele suporta PCIe 4.0 para maior velocidade de transferência de dados. Sua arquitetura de 7nm e TDP de apenas 65W garantem eficiência energética. Além disso, acompanha o cooler Wraith Stealth, garantindo ótimo resfriamento e operação silenciosa.", imagem:"/uploads/image-1738024920661-621913932.jpg" },
        { nome: 'Smart TV Samsung 50" 4K', categoria: 'Eletrônicos', subcategoria: 'TVs', estoque: 8, preco: 3499.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "A Smart TV Samsung 50 4K combina design elegante com tecnologia de ponta para transformar sua experiência de entretenimento. Com resolução Ultra HD 4K, oferece imagens nítidas, cores vibrantes e detalhes impressionantes, ideais para filmes, séries e jogos. Alimentada pelo sistema Tizen, proporciona navegação fluida e acesso rápido a aplicativos de streaming como Netflix e YouTube. Recursos como HDR garantem contraste aprimorado, enquanto conectividade Wi-Fi e Bluetooth permitem fácil integração com dispositivos. Perfeita para quem busca qualidade de imagem superior e funcionalidades modernas em uma TV espaçosa e sofisticada.", imagem: "/uploads/image-1738025400131-830327512.jpg"},
        { nome: 'Drone DJI Mini 2', categoria: 'Eletrônicos', subcategoria: 'Drones', estoque: 6, preco: 3999.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao:"O Drone DJI Mini 2 é a escolha ideal para capturar momentos incríveis com praticidade e alta qualidade. Compacto e leve, pesa menos de 249g, tornando-o fácil de transportar. Equipado com uma câmera 4K e estabilização em três eixos, oferece vídeos suaves e fotos nítidas, mesmo em condições desafiadoras. Com alcance de até 10 km e autonomia de voo de 31 minutos, permite explorar e registrar paisagens de tirar o fôlego. Recursos inteligentes, como QuickShots e retorno automático, tornam seu uso acessível tanto para iniciantes quanto para profissionais. Um companheiro perfeito para suas aventuras aéreas." , imagem:"/uploads/image-1738025436087-880941597.webp" },
        { nome: 'Impressora HP Deskjet', categoria: 'Escritório', subcategoria: 'Impressoras', estoque: 22, preco: 749.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao:"A Impressora HP DeskJet é a solução perfeita para quem busca praticidade e qualidade em suas impressões diárias. Compacta e elegante, se adapta facilmente a qualquer espaço, oferecendo impressão, cópia e digitalização em um único dispositivo. Ideal para uso doméstico ou pequenos escritórios, proporciona resultados nítidos e coloridos com economia, graças aos cartuchos de tinta acessíveis. Com conectividade simples, como Wi-Fi e suporte a impressão via dispositivos móveis, permite imprimir diretamente do smartphone ou tablet. Confiável e eficiente, é uma excelente escolha para suas necessidades do dia a dia." , imagem:"/uploads/image-1738025508884-795661210.jpg" },
        { nome: 'Pen Drive SanDisk 128GB', categoria: 'Armazenamento', subcategoria: 'Pen Drives', estoque: 100, preco: 79.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "O Pen Drive SanDisk 128GB oferece uma solução prática e rápida para armazenar e transferir seus dados com segurança. Com uma grande capacidade de 128GB, ele permite guardar uma grande quantidade de arquivos, como fotos, vídeos e documentos, sem preocupação com falta de espaço. Seu design compacto e resistente facilita o transporte e uso em diferentes dispositivos, como computadores, TVs, e outros aparelhos com entrada USB. Além disso, a confiabilidade da marca SanDisk garante desempenho consistente e durabilidade, tornando-o ideal para quem precisa de um armazenamento portátil e eficiente no dia a dia.", imagem: "/uploads/image-1738025578649-912617894.webp"},
        { nome: 'Carregador MagSafe', categoria: 'Acessórios', subcategoria: 'Apple', estoque: 30, preco: 199.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao: "O Carregador MagSafe é um acessório inovador da Apple projetado para carregar dispositivos de maneira rápida e eficiente, utilizando tecnologia magnética. Compatível com modelos mais recentes de iPhone, o MagSafe se conecta automaticamente ao dispositivo, oferecendo um encaixe perfeito e seguro, o que evita desconexões acidentais durante o carregamento. Com uma potência de até 15W, proporciona uma carga mais rápida e estável em comparação aos carregadores convencionais. Seu design minimalista e elegante combina com a estética dos aparelhos Apple, tornando-o um acessório tanto funcional quanto estiloso para quem busca praticidade e eficiência.", imagem: "/uploads/image-1738025616609-625565351.jpg"},
        { nome: 'Cabo HDMI 2.1 3M', categoria: 'Acessórios', subcategoria: 'Cabos', estoque: 80, preco: 49.0, catalogo: 'Não', favorito: false, usuario_id: 1, descricao: "O Cabo HDMI 2.1 3M oferece alta performance e velocidade de transmissão para equipamentos que exigem a mais alta qualidade de imagem e som. Com uma largura de banda de até 48 Gbps, ele suporta resoluções de até 8K a 60Hz e 4K a 120Hz, além de ser compatível com formatos de áudio como Dolby TrueHD e DTS-HD Master Audio. Ideal para conectar dispositivos como consoles de última geração, PCs, TVs e monitores, o cabo garante uma experiência de entretenimento imersiva com alta taxa de atualização e imagem sem falhas. Seu design durável e flexível, com 3 metros de comprimento, oferece maior alcance e comodidade em qualquer ambiente.", imagem:"/uploads/image-1738024640068-948581300.webp" },
        { nome: 'Roteador TP-Link AX3000', categoria: 'Redes', subcategoria: 'Roteadores', estoque: 25, preco: 399.0, catalogo: 'Não', favorito: true, usuario_id: 1, descricao:"O Roteador TP-Link AX3000 é uma solução de rede Wi-Fi 6 de alta performance, projetado para fornecer conexões rápidas e estáveis para ambientes residenciais e pequenos escritórios. Com uma velocidade combinada de até 3000 Mbps, ele oferece cobertura ampla e desempenho excepcional, mesmo em ambientes com múltiplos dispositivos conectados simultaneamente. A tecnologia Wi-Fi 6 (802.11ax) garante maior eficiência, menor latência e maior capacidade de conexão, proporcionando uma experiência de navegação fluida e sem interrupções. Além disso, o TP-Link AX3000 conta com várias portas Gigabit para conexões com fio rápidas e suporte a MU-MIMO, para atender a múltiplos dispositivos ao mesmo tempo. Seu design compacto e moderno também o torna discreto e fácil de integrar em qualquer ambiente." , imagem: "/uploads/image-1738025668676-710642575.jpg"},
      ];
      
    await Produto.bulkCreate(produtos);
    console.log('Dados de produtos inseridos com sucesso!');

    // Insere dados iniciais em `vendas` (se necessário)
    const vendas = [
      { cod_produto: 1, quantidade: 5, preco: 375.0, usuario_id: 1 },
      { cod_produto: 2, quantidade: 3, preco: 74.7, usuario_id: 1 },
    ];
    await Venda.bulkCreate(vendas);
    console.log('Dados de vendas inseridos com sucesso!');

    console.log('Todos os dados iniciais foram inseridos com sucesso!');
  } catch (err) {
    console.error('Erro ao sincronizar banco ou inserir dados iniciais:', err);
  }
})();
